name: know_the_drop
description: "A trivia app about DJ Tiësto."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/questions/
    - assets/images/
